# Generated by Django 4.1.1 on 2022-09-16 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='Project title should not exceed 100 character.', max_length=100)),
                ('project_details', models.TextField(null=True)),
                ('project_total_target', models.IntegerField(null=True)),
                ('project_start_date', models.DateField(blank=True, default=datetime.date(2022, 9, 16), null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
