# Generated by Django 4.1.1 on 2022-09-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_images',
        ),
    ]
