# Generated by Django 4.1.1 on 2022-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_total_target',
            field=models.IntegerField(null=True),
        ),
    ]
