# Generated by Django 4.1.1 on 2022-09-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_project_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
