# Generated by Django 4.1.1 on 2022-09-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_project_created_date_project_project_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_images',
            field=models.ImageField(null=True, upload_to='project/image'),
        ),
    ]
