# Generated by Django 4.1.1 on 2022-09-14 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 14), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(help_text='Project title should not exceed 100 character.', max_length=100),
        ),
    ]
