# Generated by Django 4.1.1 on 2022-09-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_project_owner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_owner',
            new_name='created_by',
        ),
    ]
