# Generated by Django 4.1.1 on 2022-09-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/base/imgs/funding-white-bk.ico', null=True, upload_to='account/image'),
        ),
    ]
