# Generated by Django 4.1.1 on 2022-09-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='account/image/john.jpg', null=True, upload_to='account/image'),
        ),
    ]
