# Generated by Django 4.1.1 on 2022-09-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='account/image/default.png', null=True, upload_to='account/image'),
        ),
    ]
